package com.sentinelx.shared

data class PrivacyReport(
    val generatedAt: Long,
    val totalAppsScanned: Int,
    val criticalApps: List<AppInfo>,
    val highRiskApps: List<AppInfo>,
    val totalAnomalies: Int,
    val recentMonitorEvents: List<MonitorEvent>,   // last 50 events from service
    val autoRevokeSuggestions: List<AppInfo>,       // apps where autoRevokeSuggested = true
    val topPermissionsByUsage: Map<String, Long>,   // permission → total ms used across all apps
    val deviceRiskScore: Int,                       // 0–100 overall device score
    val deviceRiskLevel: String
) {
    fun toShareableText(): String {
        return buildString {
            appendLine("=============================")
            appendLine("  SentinelX Privacy Report")
            appendLine("  ${generatedAt.toReadableTimestamp()}")
            appendLine("=============================")
            appendLine()
            appendLine("📊 Device Risk: ${deviceRiskScore.toRiskEmoji()} $deviceRiskLevel ($deviceRiskScore/100)")
            appendLine("📱 Apps Scanned: $totalAppsScanned")
            appendLine("🚨 Critical: ${criticalApps.size}  🔴 High: ${highRiskApps.size}")
            appendLine("⚠️  Total Anomalies: $totalAnomalies")
            appendLine()
            if (criticalApps.isNotEmpty()) {
                appendLine("🚨 CRITICAL RISK APPS:")
                criticalApps.forEach {
                    appendLine("  - ${it.appName}: ${it.riskScore}/100")
                }
                appendLine()
            }
            if (autoRevokeSuggestions.isNotEmpty()) {
                appendLine("💡 AUTO-REVOKE SUGGESTIONS:")
                autoRevokeSuggestions.forEach {
                    appendLine("  - ${it.appName} (unused ${it.lastUsedTimestamp.daysSince()}d, risk: ${it.riskLevel})")
                }
                appendLine()
            }
            if (topPermissionsByUsage.isNotEmpty()) {
                appendLine("⏱️ MOST USED PERMISSIONS TODAY:")
                topPermissionsByUsage.entries.take(5).forEach { (perm, ms) ->
                    appendLine("  - ${perm.substringAfterLast(".")} : ${ms.toReadableDuration()}")
                }
            }
            appendLine()
            appendLine("Generated by SentinelX")
        }
    }
}